######################################################################
# Automatically generated by qmake (2.01a) pon. lut 18 19:06:29 2008
######################################################################

TEMPLATE = app
TARGET = gbcflsh 
DEPENDPATH += .
INCLUDEPATH += .
#DESTDIR = build

QT += widgets

# Input
HEADERS += src/headers/About.h \
           src/headers/AbstractPort.h \
           src/headers/Console.h \
           src/headers/const.h \
           src/headers/EraseThread.h \
           src/headers/Gui.h \
           src/headers/Logic.h \
           src/headers/ReadFlashThread.h \
           src/headers/ReadRamThread.h \
           src/headers/Settings.h \
           src/headers/WriteFlashThread.h \
           src/headers/WriteRamThread.h
# Assets
HEADERS += src/assets/about.xpm \
           src/assets/flasher.xpm \
           src/assets/icon.xpm
SOURCES += src/EraseThread.cpp \
           src/gbcflsh.cpp \
           src/Logic.cpp \
           src/ReadFlashThread.cpp \
           src/ReadRamThread.cpp \
           src/Settings.cpp \
           src/WriteFlashThread.cpp \
           src/WriteRamThread.cpp
# Views
SOURCES += src/views/About.cpp \
           src/views/Gui.cpp
TRANSLATIONS += src/translations/gbcflsh_english.ts \
                src/translations/gbcflsh_french.ts \
                src/translations/gbcflsh_german.ts \
                src/translations/gbcflsh_polish.ts
RC_FILE = src/res.rc
win32 {
SOURCES += src/SerialPortWin.cpp \
           src/USBPortWin.cpp 
HEADERS += src/headers/SerialPortWin.h \
           src/headers/USBPortWin.h
LIBS += -lftd2xx
}
unix {
SOURCES += src/SerialPort.cpp \
           src/USBPort.cpp 
HEADERS += src/headers/SerialPort.h \
           src/headers/USBPort.h
LIBS += -lftdi
langpack.extra = lrelease gbcf.pro
langpack.path = /usr/share/gbcf
langpack.files = src/*.qm
exec.path = /usr/bin
exec.files = gbcflsh
config.path = ~/.config/gbcflash
config.files = gbcflash.conf
INSTALLS += langpack exec config
}
