name: Check Build
on: push

jobs:
  test-build-nix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: 'recursive'
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '5.*'
          cache: true
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake libusb-1.0-0-dev
      - name: Configure
        run: mkdir -p build && cmake -Bbuild
      - name: Build
        run: cd build && make
