name: workflow.yml
on:
  push:
    branches:
      - develop
      - main

jobs:
  test-build-nix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '5.*'
          #          modules: 'qtwidgets'
          cache: true
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential make libftdi-dev
      - name: Build
        run: make
